const SHOW_MODAL_TIMER = 'SHOW_MODAL_TIMER'
const HIDDEN_MODAL_TIMER = 'HIDDEN_MODAL_TIMER'
const ADD_TIMER = 'ADD_TIMER'
const CHANGE = 'CHANGE'
const REMOVE_TIMER = 'REMOVE_TIMER'
const STOP_TIMER = 'STOP_TIMER'
const START_TIMER = 'START_TIMER'
const RESTART_TIMER = 'RESTART_TIMER'
const REDUCE_TIME = 'REDUCE_TIME'
const UPDATE_TIMER = 'UPDATE_TIMER'
const UPDATE_TIME = 'UPDATE_TIME'
const ADD_AUDIO = 'ADD_AUDIO'
const REMOVE_AUDIO = 'REMOVE_AUDIO'

export {
  SHOW_MODAL_TIMER,
  HIDDEN_MODAL_TIMER,
  ADD_TIMER,
  CHANGE,
  REMOVE_TIMER,
  STOP_TIMER,
  START_TIMER,
  RESTART_TIMER,
  REDUCE_TIME,
  UPDATE_TIMER,
  UPDATE_TIME,
  ADD_AUDIO,
  REMOVE_AUDIO
}